CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -I./include
SRC = src/main.cpp src/audio_buffer.cpp src/wav_reader.cpp src/wav_writer.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = audio_engine.exe

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	del /Q src\*.o $(TARGET)